server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world_cari
    username: root
    password: master

#    jpa:
#      hibernate:
#        use-new-id-generator-mappings: false
    messages:
      basename: i18n/exception
      encoding: UTF-8
    jwt:
      secret: govlepel@$&amp;